#!/bin/sh


function localize {
    # What's the HOME dir?
    homedir=$(cd ~ ; pwd)
    echo $(realpath $1) | sed -rne "s|${homedir}/(.*)|\1|p"
}

SSHENDPOINT=$1
shift
for i in $* 
do 
    rsync -niae ssh $i $SSHENDPOINT:$(dirname $(localize $i)) 
done

# End ssh-push
